//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlerMvcAcesso.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class TB_AUTORIZACAO
    {
        [Key]
        public int COD_AUTORIZACAO { get; set; }
        [Required(ErrorMessage = "Obrigatório Digitar o Nome do Responsável")]
        public string NOME_RESPONSAVEL { get; set; }
        [Required(ErrorMessage = "Obrigatório Digitar o Rg do Responsável")]
        public int RG_RESPONSAVEL { get; set; }
        [Required(ErrorMessage = "*")]
        public System.DateTime DATA { get; set; }
        [Required(ErrorMessage = "*")]
        public System.TimeSpan HORA { get; set; }
        [Required(ErrorMessage = "Obrigatório Informar o Motivo")]
        public string MOTIVO { get; set; }
        public Nullable<int> COD_ALUNO { get; set; }
    
        public virtual TB_ALUNO TB_ALUNO { get; set; }
    }
}
