//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlerMvcAcesso.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class TB_ADM_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ADM_USUARIO()
        {
            this.TB_ALUNO = new HashSet<TB_ALUNO>();
        }
    
        [Key]
        public int COD_ADM_USUARIO { get; set; }
        [Required(ErrorMessage ="Obrigatório Digitar o Nome do Adm")]
        public string NOME_ADM { get; set; }
        [Required(ErrorMessage = "Obrigatório Digitar o Sobrenome do Adm")]
        public string SOBRENOME { get; set; }
        [Required(ErrorMessage = "Obrigatório Digitar o Email do Adm")]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Obrigatório Digitar o Senha do Adm")]
        public string SENHA { get; set; }
        [Required(ErrorMessage = "Obrigatório Informar o Perfil do Adm")]
        public string PERFIL { get; set; }
        [Required(ErrorMessage = "Obrigatório Informar o Status do Adm")]
        public string ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ALUNO> TB_ALUNO { get; set; }
    }
}
