//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlerMvcAcesso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CURSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CURSO()
        {
            this.TB_TURMA = new HashSet<TB_TURMA>();
        }
    
        public int COD_CURSO { get; set; }
        public string NOME_CURSO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TURMA> TB_TURMA { get; set; }
    }
}
