//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlerMvcAcesso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TURMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TURMA()
        {
            this.TB_ALUNO_TURMA = new HashSet<TB_ALUNO_TURMA>();
        }
    
        public int COD_TURMA { get; set; }
        public string SERIE { get; set; }
        public string PERIODO { get; set; }
        public System.TimeSpan HORA_ENTRADA { get; set; }
        public System.TimeSpan HORA_SAIDA { get; set; }
        public Nullable<int> COD_CURSO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ALUNO_TURMA> TB_ALUNO_TURMA { get; set; }
        public virtual TB_CURSO TB_CURSO { get; set; }
    }
}
